Repository Prosoft-Skynet/EasySave, pull requests merged in 2025-02, with the labels that each got.

#10 create main interface
  EasySaveConsole/Program.cs
Labels: enhancement

#15 EasySaveNamespace.Backup
  EasySaveConsole/src/EasySaveNamespace.Backup/BackupJob.cs
  EasySaveConsole/src/EasySaveNamespace.Backup/BackupJobFactory.cs
  EasySaveConsole/src/EasySaveNamespace.Backup/BackupService.cs
  EasySaveConsole/src/EasySaveNamespace.Backup/CompleteBackupStrategy.cs
  EasySaveConsole/src/EasySaveNamespace.Backup/DifferentialBackupStrategy.cs
  EasySaveConsole/src/EasySaveNamespace.Backup/IBackupTypeStrategy.cs
Labels: enhancement

#18 Ajout feature interface
  EasySaveConsole/Program.cs
Labels: enhancement

#23 LanguageManager V1.0
  EasySaveConsole/Program.cs
  EasySaveConsole/src/EasySaveNamespace.Language/EnLanguage.cs
  EasySaveConsole/src/EasySaveNamespace.Language/FrLanguage.cs
  EasySaveConsole/src/EasySaveNamespace.Language/Language.cs
  EasySaveConsole/src/EasySaveNamespace.Language/LanguageManager.cs
  EasySaveConsole/src/EasySaveNamespace/EasySave.cs
Labels: enhancement

#22 Add EasySaveNamespace.State #21
  EasySaveConsole/src/EasySaveNamespace.State/StateEntry.cs
  EasySaveConsole/src/EasySaveNamespace.State/StateManager.cs
  EasySaveConsole/src/EasySaveNamespace/BackupManager.cs
Labels: enhancement

#20 add documentation on EasySaveNamespace and EasySaveNamespace.Backup
  EasySaveConsole/src/EasySaveNamespace.Backup/BackupJob.cs
  EasySaveConsole/src/EasySaveNamespace.Backup/BackupJobFactory.cs
  EasySaveConsole/src/EasySaveNamespace.Backup/BackupService.cs
  EasySaveConsole/src/EasySaveNamespace.Backup/CompleteBackupStrategy.cs
  EasySaveConsole/src/EasySaveNamespace.Backup/DifferentialBackupStrategy.cs
  EasySaveConsole/src/EasySaveNamespace.Backup/IBackupTypeStrategy.cs
  EasySaveConsole/src/EasySaveNamespace/BackupManager.cs
  EasySaveConsole/src/EasySaveNamespace/EasySave.cs
Labels: documentation

#26 Commentary LanguageManager
  EasySaveConsole/src/EasySaveNamespace.Language/EnLanguage.cs
  EasySaveConsole/src/EasySaveNamespace.Language/FrLanguage.cs
  EasySaveConsole/src/EasySaveNamespace.Language/Language.cs
  EasySaveConsole/src/EasySaveNamespace.Language/LanguageManager.cs
  EasySaveConsole/src/EasySaveNamespace/EasySave.cs
Labels: documentation

#25 Fix backup names and case 7
  EasySaveConsole/Program.cs
  EasySaveConsole/src/EasySaveNamespace.Language/EnLanguage.cs
  EasySaveConsole/src/EasySaveNamespace.Language/FrLanguage.cs
  EasySaveConsole/src/EasySaveNamespace.State/StateManager.cs
Labels: bug

#30 Add documentation in English
  EasySaveConsole/src/EasySaveNamespace.Backup/BackupJob.cs
  EasySaveConsole/src/EasySaveNamespace.Backup/BackupJobFactory.cs
  EasySaveConsole/src/EasySaveNamespace.Backup/BackupService.cs
  EasySaveConsole/src/EasySaveNamespace.Backup/CompleteBackupStrategy.cs
  EasySaveConsole/src/EasySaveNamespace.Backup/DifferentialBackupStrategy.cs
  EasySaveConsole/src/EasySaveNamespace.Backup/IBackupTypeStrategy.cs
  EasySaveConsole/src/EasySaveNamespace.State/StateEntry.cs
  EasySaveConsole/src/EasySaveNamespace.State/StateManager.cs
  EasySaveConsole/src/EasySaveNamespace/BackupManager.cs
  EasySaveConsole/src/EasySaveNamespace/EasySave.cs
Labels: documentation

#31 Translate Comments
  EasySaveConsole/Program.cs
  EasySaveConsole/src/EasySaveNamespace.State/StateEntry.cs
  EasySaveConsole/src/EasySaveNamespace.State/StateManager.cs
Labels: documentation

#32 Fix Documentation to English
  EasySaveConsole/src/EasySaveNamespace.CLI/CLI.cs
  EasySaveConsole/src/EasySaveNamespace.Language/EnLanguage.cs
  EasySaveConsole/src/EasySaveNamespace.Language/FrLanguage.cs
  EasySaveConsole/src/EasySaveNamespace.Language/Language.cs
  EasySaveConsole/src/EasySaveNamespace.Language/LanguageManager.cs
Labels: documentation

#33 Add Readme
  README.md
Labels: documentation

#34 Feature/add logs
  EasySaveConsole/EasySaveConsole.csproj
  EasySaveConsole/Program.cs
  EasySaveConsole/src/EasySaveNamespace.Language/EnLanguage.cs
  EasySaveConsole/src/EasySaveNamespace.Language/FrLanguage.cs
  EasySaveConsole/src/EasySaveNamespace.State/StateManager.cs
  EasySaveLogger/EasySaveLogger.csproj
  EasySaveLogger/EasySaveLogger.sln
  EasySaveLogger/LogEntry.cs
  EasySaveLogger/Logger.cs
  EasySaveLogger/Properties/AssemblyInfo.cs
  EasySaveLogger/app.config
  EasySaveLogger/packages.config
Labels: enhancement

#36 Merge Version 1.0.0 console version
  EasySave.sln
  EasySaveConsole/EasySaveConsole.csproj
  EasySaveConsole/Program.cs
  EasySaveConsole/src/EasySaveNamespace.Backup/BackupJob.cs
  EasySaveConsole/src/EasySaveNamespace.Backup/BackupJobFactory.cs
  EasySaveConsole/src/EasySaveNamespace.Backup/BackupService.cs
  EasySaveConsole/src/EasySaveNamespace.Backup/CompleteBackupStrategy.cs
  EasySaveConsole/src/EasySaveNamespace.Backup/DifferentialBackupStrategy.cs
  EasySaveConsole/src/EasySaveNamespace.Backup/IBackupTypeStrategy.cs
  EasySaveConsole/src/EasySaveNamespace.CLI/CLI.cs
  EasySaveConsole/src/EasySaveNamespace.Language/EnLanguage.cs
  EasySaveConsole/src/EasySaveNamespace.Language/FrLanguage.cs
  EasySaveConsole/src/EasySaveNamespace.Language/Language.cs
  EasySaveConsole/src/EasySaveNamespace.Language/LanguageManager.cs
  EasySaveConsole/src/EasySaveNamespace.State/StateEntry.cs
  EasySaveConsole/src/EasySaveNamespace.State/StateManager.cs
  EasySaveConsole/src/EasySaveNamespace/BackupManager.cs
  EasySaveConsole/src/EasySaveNamespace/EasySave.cs
  EasySaveLogger/EasySaveLogger.csproj
  EasySaveLogger/EasySaveLogger.sln
  EasySaveLogger/LogEntry.cs
  EasySaveLogger/Logger.cs
  EasySaveLogger/Properties/AssemblyInfo.cs
  EasySaveLogger/app.config
  EasySaveLogger/packages.config
  README.md
Labels: enhancement

#38 Add xml format for logs
  EasySaveConsole/Program.cs
  EasySaveConsole/src/EasySaveNamespace.Language/EnLanguage.cs
  EasySaveConsole/src/EasySaveNamespace.Language/FrLanguage.cs
  EasySaveConsole/src/EasySaveNamespace.State/StateManager.cs
  EasySaveLogger/LogEntry.cs
  EasySaveLogger/Logger.cs
  EasySaveLogger/src/EasySaveNamespace.Logger/ILogFormatter.cs
  EasySaveLogger/src/EasySaveNamespace.Logger/JsonLogFormatter.cs
  EasySaveLogger/src/EasySaveNamespace.Logger/LogEntry.cs
  EasySaveLogger/src/EasySaveNamespace.Logger/Logger.cs
  EasySaveLogger/src/EasySaveNamespace.Logger/XmlLogFormatter.cs
Labels: enhancement

#39 fix case error with xml format
  EasySaveConsole/Program.cs
  EasySaveConsole/src/EasySaveNamespace.Language/EnLanguage.cs
  EasySaveConsole/src/EasySaveNamespace.Language/FrLanguage.cs
  EasySaveLogger/src/EasySaveNamespace.Logger/LogEntry.cs
  EasySaveLogger/src/EasySaveNamespace.Logger/Logger.cs
Labels: bug

#40 Merge dev in main for v1.1
  EasySaveConsole/Program.cs
  EasySaveConsole/src/EasySaveNamespace.Language/EnLanguage.cs
  EasySaveConsole/src/EasySaveNamespace.Language/FrLanguage.cs
  EasySaveConsole/src/EasySaveNamespace.State/StateManager.cs
  EasySaveLogger/LogEntry.cs
  EasySaveLogger/Logger.cs
  EasySaveLogger/src/EasySaveNamespace.Logger/ILogFormatter.cs
  EasySaveLogger/src/EasySaveNamespace.Logger/JsonLogFormatter.cs
  EasySaveLogger/src/EasySaveNamespace.Logger/LogEntry.cs
  EasySaveLogger/src/EasySaveNamespace.Logger/Logger.cs
  EasySaveLogger/src/EasySaveNamespace.Logger/XmlLogFormatter.cs
Labels: enhancement

#43 Deletion of the backups limitation
  EasySaveConsole/Program.cs
  EasySaveConsole/src/EasySaveNamespace.Language/EnLanguage.cs
  EasySaveConsole/src/EasySaveNamespace.Language/FrLanguage.cs
Labels: enhancement

#55 New log feature added with the interface
  EasySaveGUI/EasySaveGUI.csproj
  EasySaveGUI/ViewModels/MainViewModel.cs
  EasySaveGUI/Views/MainWindow.xaml
Labels: enhancement

#57 Fix Backup Differential and Complete Bugs
  EasySaveCore/src/Backup/CompleteBackupStrategy.cs
  EasySaveCore/src/Backup/DifferentialBackupStrategy.cs
Labels: bug

#58 CryptoSoft
  EasySaveCore/src/Controller/BackupManager.cs
  EasySaveCore/src/Controller/EasySave.cs
  EasySaveCore/src/CryptoSoft/CryptoSoft.cs
  EasySaveCore/src/CryptoSoft/FileManager.cs
  EasySaveCore/src/Language/EnLanguage.cs
  EasySaveCore/src/Language/FrLanguage.cs
  EasySaveGUI/Helpers/CustomInputDialog.cs
  EasySaveGUI/ViewModels/MainViewModel.cs
  EasySaveLogger/src/Logger/LogEntry.cs
  EasySaveLogger/src/Logger/Logger.cs
Labels: enhancement

#60 add persitence for job of backup
  EasySaveCore/src/Backup/BackupJob.cs
  EasySaveCore/src/Backup/CompleteBackupStrategy.cs
  EasySaveCore/src/Controller/BackupManager.cs
  EasySaveCore/src/CryptoSoft/CryptoSoft.cs
  EasySaveCore/src/CryptoSoft/FileManager.cs
  EasySaveGUI/ViewModels/MainViewModel.cs
Labels: enhancement

#64 Feature/ban business aplications
  EasySaveCore/src/Backup/BackupJob.cs
  EasySaveCore/src/Backup/BackupService.cs
  EasySaveCore/src/Backup/CompleteBackupStrategy.cs
  EasySaveCore/src/Backup/DifferentialBackupStrategy.cs
  EasySaveCore/src/Backup/IBackupTypeStrategy.cs
  EasySaveCore/src/Language/EnLanguage.cs
  EasySaveCore/src/Language/FrLanguage.cs
  EasySaveGUI/ViewModels/MainViewModel.cs
  EasySaveGUI/Views/MainWindow.xaml
  EasySaveGUI/Views/SettingsWindow.xaml
  EasySaveGUI/Views/SettingsWindow.xaml.cs
Labels: enhancement

#65 Refactoring to MVVM infrastructure
  EasySaveConsole/Assets/JSONs/words.json
  EasySaveConsole/CLI.cs
  EasySaveConsole/Program.cs
  EasySaveCore/src/Backup/BackupJob.cs
  EasySaveCore/src/Backup/BackupService.cs
  EasySaveCore/src/Controller/EasySave.cs
  EasySaveCore/src/Language/EnLanguage.cs
  EasySaveCore/src/Language/FrLanguage.cs
  EasySaveCore/src/Language/Language.cs
  EasySaveCore/src/Language/LanguageManager.cs
  EasySaveCore/src/Models/BackupJobModel.cs
  EasySaveCore/src/Models/StateModel.cs
  EasySaveCore/src/Models/WordModel.cs
  EasySaveCore/src/Services/BackupJobServices/BackupJobFactory.cs
  EasySaveCore/src/Services/BackupJobServices/BackupService.cs
  EasySaveCore/src/Services/BackupJobServices/CompleteBackupStrategy.cs
  EasySaveCore/src/Services/BackupJobServices/DifferentialBackupStrategy.cs
  EasySaveCore/src/Services/BackupJobServices/IBackupTypeStrategy.cs
  EasySaveCore/src/Services/BusinessApplicationService.cs
  EasySaveCore/src/Services/CryptoSoftService.cs
  EasySaveCore/src/Services/FileService.cs
  EasySaveCore/src/Services/LanguageService.cs
  EasySaveCore/src/Services/StateService.cs
  EasySaveGUI/Assets/JSONs/words.json
  EasySaveGUI/ViewModels/MainViewModel.cs
  EasySaveGUI/ViewModels/SettingsViewModel.cs
  EasySaveGUI/Views/SettingsWindow.xaml.cs
Labels: enhancement

#73 the language is now resgistered in a File, so every time the Language…
  EasySaveCore/src/Services/LanguageService.cs
Labels: bug

#75 stop break and start backup
  EasySaveCore/src/Services/BackupJobServices/BackupService.cs
  EasySaveCore/src/Services/BackupJobServices/CompleteBackupStrategy.cs
  EasySaveCore/src/Services/BackupJobServices/DifferentialBackupStrategy.cs
  EasySaveCore/src/Services/BackupJobServices/IBackupTypeStrategy.cs
  EasySaveGUI/Assets/JSONs/words.json
  EasySaveGUI/ViewModels/MainViewModel.cs
  EasySaveGUI/Views/MainWindow.xaml
Labels: enhancement

#76 Update Readme
  README.md
Labels: documentation

#74 add possibly extension crypt
  EasySaveCore/src/Services/BackupJobServices/BackupService.cs
  EasySaveGUI/Assets/JSONs/words.json
  EasySaveGUI/ViewModels/MainViewModel.cs
  EasySaveGUI/ViewModels/SettingsViewModel.cs
  EasySaveGUI/Views/SettingsWindow.xaml
Labels: enhancement

#79 Remove Ban App
  EasySaveCore/src/Services/BackupJobServices/BackupService.cs
  EasySaveCore/src/Services/BusinessApplicationService.cs
  EasySaveGUI/Assets/JSONs/words.json
  EasySaveGUI/ViewModels/SettingsViewModel.cs
  EasySaveGUI/Views/SettingsWindow.xaml
Labels: enhancement

#83 Code ql integration
  .github/workflows/codeql.yml
Labels: enhancement

#87 Mono instance cryptoSoft
  EasySaveCore/src/Services/BackupJobServices/BackupService.cs
  EasySaveCore/src/Services/CryptoSoftService.cs
Labels: enhancement

#88 Add all uml in project
  UML/UML V1.1/Diagramme d'activité V1.1.pdf
  UML/UML V1.1/Diagramme de classe V1.1.svg
  UML/UML V1.1/Diagramme de classe V1.1.txt
  UML/UML V1.1/Diagramme de séquence V1.1.svg
  UML/UML V1.1/Diagramme de séquence V1.1.txt
  UML/UML V1.1/Diagramme de use-cases V1.1.pdf
  UML/UML V1/Diagramme d'activité V1.pdf
  UML/UML V1/Diagramme de classe V1.svg
  UML/UML V1/Diagramme de classe V1.txt
  UML/UML V1/Diagramme de séquence V1.svg
  UML/UML V1/Diagramme de séquence V1.txt
  UML/UML V1/Diagramme de use-cases V1.pdf
  UML/UML V2/Diagramme d'activité V2.pdf
  UML/UML V2/Diagramme de classe V2.svg
  UML/UML V2/Diagramme de classe V2.txt
  UML/UML V2/Diagramme de séquence V2.svg
  UML/UML V2/Diagramme de séquence V2.txt
  UML/UML V2/Diagramme use-cases V2.pdf
  UML/UML V3/Diagramme d'activité V3.pdf
  UML/UML V3/Diagramme de classe V3.svg
  UML/UML V3/Diagramme de classe V3.txt
  UML/UML V3/Diagramme de séquence V3.svg
  UML/UML V3/Diagramme de séquence V3.txt
  UML/UML V3/Diagramme de use-cases V3.pdf
Labels: documentation

#89 Feat/parralel jobs
  EasySaveCore/src/Services/BackupJobServices/BackupJobFactory.cs
  EasySaveCore/src/Services/BackupJobServices/BackupService.cs
  EasySaveGUI/Assets/JSONs/words.json
  EasySaveGUI/ViewModels/MainViewModel.cs
  EasySaveGUI/Views/MainWindow.xaml
Labels: enhancement
